name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libayatana-appindicator3-dev \
            libasound2-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libxdo-dev \
            librsvg2-dev \
            libglib2.0-dev \
            pkg-config \
            patchelf

      - name: Check pkg-config for glib
        run: pkg-config --cflags --libs glib-2.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv (fast virtualenv manager)
        run: pip install uv

      - name: Create and activate venv
        run: |
          uv venv .venv
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: pip install pytest maturin

      - name: Build extension (release mode)
        run: maturin develop --release

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings
